version: '3.5'
services:
  https-portal:
    container_name: ssl
    image: steveltn/https-portal:1
    depends_on:
        - php
    ports:
        - 80:80
        - 443:443
    restart: always
    volumes:
       - ./ssl_certs:/var/lib/https-portal
    environment:
        DOMAINS: 'tareas.lucaspintos.tech -> http://54.221.169.122:8080 #production'

  php:
    container_name: php
    image: lucaspintos909/task-manager-php:latest
    ports:
      - 8080:80
    volumes:
      - ./src/config/config.php:/var/www/html/config/config.php
    depends_on:
      - db
    networks:
      - docker-net

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: lucas
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3360:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql # Archivo para inicializar la creacion de las tablas y base de datos
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge
