version: '3.5'
services:
  php:
    container_name: php
    build:
      context: ./
    ports: 
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: lucas
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3360:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql # Archivo para inicializar las tablas y base de datos

